services:
  chainlit:
    build: .
    container_name: chainlit_ma
    hostname: chainlit_ma
    restart: unless-stopped
    ports:
      - "8008:8000"
    networks:
      - default

  chainlit-db:
    image: postgres:16
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=chainlit
      - POSTGRES_PASSWORD=chainlit
      - POSTGRES_DB=chainlit
    container_name: chainlit-db
    hostname: chainlit-db
    restart: unless-stopped
    ports:
      - "5444:5432"
    networks:
      - default

  localstack:
    image: localstack/localstack:latest
    environment:
      SERVICES: s3
    ports:
      - 4566:4566
    volumes:
      - ./localstack/localstack-script.sh:/etc/localstack/init/ready.d/script.sh
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - default

networks:
  default: